project:
  type: website
  output-dir: docs
  resources: 
    - "*.gpkg"
    - "*.csl"
    - "*.bib"
  render:
    - "*.qmd"
    - "!km_population_20230625.qmd"

lang: ko-KR

website:
  title: "지도제작 대회"
  page-footer:
    left: "[Quarto](https://quarto.org/) 로 제작"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: "Home"
      - text: "지도 그리기"
        menu: 
          - href: day_01.qmd
            text: "지도 색칠"
          - href: day_02.qmd
            text: "인구수 점(Point)"
          - href: day_03.qmd
            text: "스파이크(Spike map)"
          - href: day_04.qmd
            text: "지형도(Topographic map)"
          - href: day_05.qmd
            text: "3D 표고 지도(독도)"
          - href: day_06.qmd
            text: "아시아국가 실업율(%)"
          - href: day_07.qmd
            text: "인터랙티브 지도(Mapview)"
          - href: day_08.qmd
            text: "지오코딩"
          - href: day_heatmap.qmd
            text: "열지도(heatmap)"
            
      - text: "GIS 분석"
        menu: 
          - href: spatial_map.qmd
            text: "지도(Map)"
          - href: jeju_map.qmd
            text: "제주도 높이 지도"
          - href: yellow_sea.qmd
            text: "황해"
          - href: yellow_sea2.qmd
            text: "황해2"
          - href: gg_analytics_center.qmd
            text: "경기 데이터 분석 센터"            
          - href: km_school.qmd
            text: "광명시 학교와 CCTV"

      - text: "제21대 국회의원 선거"
        menu: 
          - href: precinct.qmd
            text: "국회의원 선거구"
          - href: minju_nomination.qmd
            text: "민주당 전략공천 성과"
          - href: precinct_history.qmd
            text: "선거구와 정수"
          - href: electorate.qmd
            text: "변경된 선거구"
          - href: precinct_district.qmd
            text: "선거구 평균 인구수"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: css/quarto.scss
    code-link: true
    code-fold: show
    code-tools: true
    code-block-bg: "white"
    code-block-border-left: "#31BAE9"
    highlight-style: github
    toc: true
  


