project:
  type: website
  output-dir: docs
  resources: 
    - "*.gpkg"
    - "*.csl"
    - "*.bib"
  render:
    - "*.qmd"
    - "!km_population_20230625.qmd"

lang: ko-KR

website:
  title: "지도제작 대회"
  page-footer:
    left: "[Quarto](https://quarto.org/) 로 제작"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: "Home"
      - text: "지도 그리기"
        menu: 
          - href: day_01.qmd
            text: "지도 색칠"
          - href: day_02.qmd
            text: "인구수 점(Point)"
          - href: day_03.qmd
            text: "스파이크(Spike map)"
          - href: day_04.qmd
            text: "지형도(Topographic map)"
          - href: day_05.qmd
            text: "3D 표고 지도(독도)"
          - href: day_06.qmd
            text: "아시아국가 실업율(%)"
          - href: day_07.qmd
            text: "인터랙티브 지도(Mapview)"
          - href: day_08.qmd
            text: "지오코딩"
          - href: day_heatmap.qmd
            text: "열지도(heatmap)"
          - href: spatial_basics.qmd
            text: "지도 기본기"
          - href: tour.qmd
            text: "대통령 해외순방"
            
      - text: "GIS 분석&챗GPT"
        menu: 
          - href: spatial_map.qmd
            text: "지도(Map)"
          - href: jeju_map.qmd
            text: "제주도 높이 지도"
          - href: yellow_sea.qmd
            text: "황해"
          - href: yellow_sea2.qmd
            text: "황해2"
          - href: gg_analytics_center.qmd
            text: "경기 데이터 분석 센터"            
          - href: km_school.qmd
            text: "광명시 학교와 CCTV"
          - text: "----------------"
          - href: km_BitGPT.qmd
            text: "Code Interpreter"
            
      - text: "시각화"
        menu: 
          - href: movie.qmd
            text: "한국영화"

      - text: "제21대 국회의원 선거(I)"
        menu: 
          - href: precinct.qmd
            text: "국회의원 선거구"
          - href: minju_nomination.qmd
            text: "민주당 전략공천 성과"
          - href: precinct_history.qmd
            text: "선거구와 정수"
          - href: electorate.qmd
            text: "변경된 선거구"
          - href: precinct_district.qmd
            text: "선거구 평균 인구수"
          - href: district_issue.qmd
            text: "인구수 문제 선거구"
          - href: kwangmyung.qmd
            text: "광명시(총/대/지)"
          - href: approval_rate.qmd
            text: "대통령 지지율"
          - href: minju_party.qmd
            text: "민주당은 전국정당(?)"
          - href: by_election.qmd
            text: "재보궐: 강서구청장"
          - href: by_election_dong.qmd
            text: "재보궐: 강서구청장(동별)"
          - href: after_by_election.qmd
            text: "서울 재보궐 이후"
          - href: gs_position.qmd
            text: "재보궐: 강서구 위치"            
          - text: "----------------"
          - href: realmeter_metro.qmd
            text: "리얼미터 PDF"
          - href: gallop_metro.qmd
            text: "한국갤럽 PDF"
          - href: nbs_metro.qmd
            text: "전국지표조사 PDF"

      - text: "제21대 국회의원 선거(II)"
        menu: 
          - href: legislators.qmd
            text: "권역별 의석수 변화"
          - href: candidate.qmd
            text: "예비 후보자"
          - href: district_chair.qmd
            text: "지역/당협 위원장"
          - href: watermellon.qmd
            text: "수박 당도 선별기"
          - href: sido_legislator.qmd
            text: "시도별 역대 국회의원"
          - href: metro_people_power.qmd
            text: "수도권 국힘의원"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: css/quarto.scss
    code-link: true
    code-fold: show
    code-tools: true
    code-block-bg: "white"
    code-block-border-left: "#31BAE9"
    highlight-style: github
    toc: true
  


