project:
  type: website
  output-dir: docs
  resources: 
    - "*.gpkg"
    - "*.csl"
    - "*.bib"

lang: ko-KR

website:
  title: "지도제작 대회"
  page-footer:
    left: "[Quarto](https://quarto.org/) 로 제작"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: "Home"
      - text: "지도 그리기"
        menu: 
          - href: day_01.qmd
            text: "지도 색칠"
          - href: day_02.qmd
            text: "인구수 점(Point)"
          - href: day_03.qmd
            text: "스파이크(Spike map)"
          - href: day_04.qmd
            text: "지형도(Topographic map)"
          - href: day_05.qmd
            text: "3D 표고 지도(독도)"
          - href: day_06.qmd
            text: "아시아국가 실업율(%)"
          - href: day_07.qmd
            text: "인터랙티브 지도(Mapview)"
          - href: day_08.qmd
            text: "지오코딩"
  
format:
  html:
    theme: 
      - cosmo
      - css/quarto.scss      
    toc: true



