project:
  type: website
  output-dir: docs

lang: ko-KR

website:
  title: "지도제작 대회"
  page-footer:
    left: "[Quarto](https://quarto.org/) 로 제작"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: "Home"
      - text: "지도 그리기"
        menu: 
          - href: day_01.qmd
            text: "지도 색칠"
          - href: day_02.qmd
            text: "인구수 점(Point)"
  
format:
  html:
    theme: 
      - cosmo
      - css/quarto.scss      
    toc: true



