project:
  type: website

website:
  title: "지도제작 대회"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - day_01.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



