project:
  type: website
  output-dir: docs

website:
  title: "지도제작 대회"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: day_01.qmd
        text: "점(Point)"
      - href: day_02.qmd
        text: "`elevatr` 고도"        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



