---
title: "지도제작 대회"
subtitle: "민주당은 전국정당(?)"
description: |
  민주당은 전국정당인가?
author:
  - name: 이광춘
    url: https://www.linkedin.com/in/kwangchunlee/
    affiliation: 한국 R 사용자회
    affiliation-url: https://github.com/bit2r
title-block-banner: true
format:
  html:
    theme: flatly
    code-fold: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    toc-title: 목차
    number-sections: true
    highlight-style: github    
    self-contained: false
    default-image-extension: jpg
filters:
   - lightbox
lightbox: auto
link-citations: true
knitr:
  opts_chunk: 
    eval: true
    message: false
    warning: false
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true
editor_options: 
  chunk_output_type: console
---


# 데이터셋

## 당원 통계

```{r}
library(gt)
library(gtExtras)
library(tidyverse)

# Creating the tibble using tribble
mage_raw <- tribble(
  ~`연령`, ~비율,
  "10대후반", "0.1%",
  "20_24", "1.7%",
  "25_29", "4.2%",
  "30_34", "5.3%",
  "35_39", "6.3%",
  "40_44", "9.8%",
  "45_49", "12.2%",
  "50_54", "15.8%",
  "55_59", "13.8%",
  "60_64", "12.8%",
  "65_69", "8.1%",
  "70+", "10.0%"
)

mage_tbl <- mage_raw |> 
  mutate(비율 = parse_number(비율)/100) |> 
  mutate(당원수 = 비율 * 2454332)

mage_tbl |> 
  gt::gt() |> 
  fmt_percent(columns = 비율, decimals = 1) |> 
  fmt_integer(columns = 당원수) |> 
  cols_align("center") |> 
  ## 표 전체 합계 -------------- -----------------------
  grand_summary_rows(
    columns = 당원수,
    fns =  list(label = "합계", fn = "sum"),
    fmt = ~ fmt_integer(.),
    side = "top"
  )  |> 
  grand_summary_rows(
    columns = 비율,
    fns =  list(label = "합계", fn = "sum"),
    fmt = ~ fmt_percent(., decimals = 0),
    side = "top"
  ) |> 
  gt_theme_538()
```

## 시도별

```{r}
# tribble을 사용하여 tibble 생성
sido_raw <- tribble(
  ~`권리당원`, ~`당원수`, ~`비중`, ~`선거인수`, ~`비중`,
  "서울", 444775, "18.1%", 8378339, "18.9%",
  "부산", 54950, "2.2%", 2916832, "6.6%",
  "대구", 21011, "0.9%", 2044579, "4.6%",
  "인천", 88387, "3.6%", 2534338, "5.7%",
  "광주", 185858, "7.6%", 1206886, "2.7%",
  "대전", 67016, "2.7%", 1233557, "2.8%",
  "울산", 36175, "1.5%", 941189, "2.1%",
  "세종", 12459, "0.5%", 292259, "0.7%",
  "경기", 500892, "20.4%", 11497206, "26.0%",
  "강원", 61088, "2.5%", 1336080, "3.0%",
  "충북", 67330, "2.7%", 1368779, "3.1%",
  "충남", 121512, "5.0%", 1803096, "4.1%",
  "전북", 326518, "13.3%", 1532133, "3.5%",
  "전남", 304151, "12.4%", 1580098, "3.6%",
  "경북", 22126, "0.9%", 2268707, "5.1%",
  "경남", 77845, "3.2%", 2804287, "6.3%",
  "제주", 60667, "2.5%", 565084, "1.3%"
)

sido_raw |> 
  janitor::clean_names(ascii = FALSE) |> 
  select(시도명 = 권리당원, 당원수, 선거인수) |> 
  pivot_longer(당원수:선거인수, names_to = "구분", values_to = "인구수") |> 
  group_by(구분) |> 
  mutate(비율 = 인구수/sum(인구수)) |> 
  # 시각화
  ggplot(aes(x = fct_reorder(시도명, -비율), y = 비율, color = 구분, group = 구분)) +
    geom_point() +
    geom_line()
  

```

## 행안부 인구통계

```{r}
age_raw <- readxl::read_excel("data/혁신안_202307_202307_연령별_월간.xlsx", skip = 3)

male_tbl<- age_raw |> 
  janitor::clean_names(ascii = FALSE)  |> 
  select(c("행정기관코드", "행정기관", "남_인구수", "연령구간인구수_4", 
          "x0_4세_5", "x5_9세_6", "x10_14세_7", "x15_19세_8", "x20_24세_9", 
          "x25_29세_10", "x30_34세_11", "x35_39세_12", "x40_44세_13", 
          "x45_49세_14", "x50_54세_15", "x55_59세_16", "x60_64세_17", 
          "x65_69세_18", "x70_74세_19", "x75_79세_20", "x80_84세_21", 
          "x85_89세_22", "x90_94세_23", "x95_99세_24", "x100세_이상_25")) |> 
  pivot_longer(starts_with("x"), names_to = "연령", values_to = "인구수") |> 
  mutate(성별 = "남") |> 
  select(행정기관, 성별, 연령, 인구수)
  

female_tbl <- age_raw |> 
  janitor::clean_names(ascii = FALSE)  |> 
  select(c("행정기관코드", "행정기관", "여_인구수", "연령구간인구수_27", 
           "x0_4세_28", "x5_9세_29", "x10_14세_30", "x15_19세_31", 
           "x20_24세_32", "x25_29세_33", "x30_34세_34", "x35_39세_35", 
           "x40_44세_36", "x45_49세_37", "x50_54세_38", "x55_59세_39", 
           "x60_64세_40", "x65_69세_41", "x70_74세_42", "x75_79세_43", 
           "x80_84세_44", "x85_89세_45", "x90_94세_46", "x95_99세_47", "x100세_이상_48")) |> 
  pivot_longer(starts_with("x"), names_to = "연령", values_to = "인구수") |> 
  mutate(성별 = "여") |> 
  select(행정기관, 성별, 연령, 인구수)

age_tbl <- bind_rows(male_tbl, female_tbl) |> 
  filter(!str_detect(행정기관, "전국")) |> 
  mutate(연령 = str_extract(연령, '(\\d{1,2}_\\d{1,2})'))  |> 
  mutate(연령대 = case_when(str_detect(연령, "(0_4)|(5_9)|(10_14)|(15_19)") ~ "-19",
                              str_detect(연령, "(70_74)|(75_79)|(80_84)|(85_89)|(90_94)") ~ "70+",
                              is.na(연령) ~ "70+",
                              TRUE ~ 연령)) |> 
  mutate(인구수 = parse_number(인구수))

# age_tbl |> 
#   write_rds("data/혁신안_2023년_연령인구수.rds")
```

# 분석

## 연령비교

```{r}
mage_temp <- mage_tbl |> 
  filter(연령 != "10대후반")

age_temp <- age_tbl |> 
  filter(!str_detect(연령, "(0_4)|(5_9)|(10_14)|(15_19)")) |>   
  group_by(연령) |> 
  summarise(인구수 = sum(인구수)) |> 
  mutate(인구비율 = 인구수 / sum(인구수))

full_join(mage_temp, age_temp)

age_tbl |> 
  filter(str_detect(연령, "40"))

```


